# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13dfad62e169b03ee90e612267fd68f4c02ffc8e61ca4c730c9bcc5b18ffb0f1d7bda0a3338d22e8bd886248c3cfba462054412b3d7af0369b0ff6d835f1b60e

test:
  secret_key_base: 7b1a3fbcb328dfdcf452645a6a2007e2d4be1b6ed7420e55f3ca600c7eb8ed747d5bc34910dd2226c184b57041dcfe54d5d1a314249b24582a719543166c94e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
